---
- name: Install libvirt
  hosts: localhost
  tasks:
    - name: Check Updates
      shell: |
        #!/bin/sh
        /usr/bin/paru -Qu | wc -l
      register: check_updates
      changed_when: check_updates.stdout != "0"
      notify: Update Packages

    - name: Check Missing Packages
      shell: |
        #!/bin/bash
        comm -23 <(echo "{{ packages | join(' ') }}" | tr " " "\n" | sort) <(paru -Q | cut -d ' ' -f 1 | sort)
      register: missing_packages
      changed_when: missing_packages.stdout_lines | length != 0
      notify: Install Missing Packages
      vars:
        packages:
          - libvirt
          - qemu-base
          - virt-manager
          - virt-viewer
          - dnsmasq
          - bridge-utils
          - openbsd-netcat
          - vde2
          - dmidecode
          - libguestfs

    - name: Enable User Account `libvirt`
      become: true
      become_user: root
      lineinfile:
        dest: /etc/libvirt/libvirtd.conf
        state: present
        regexp: '#unix_sock_group = "libvirt"'
        line: 'unix_sock_group = "libvirt"'

    - name: Configure Unix Socket Permissions `libvirt`
      become: true
      become_user: root
      lineinfile:
        dest: /etc/libvirt/libvirtd.conf
        state: present
        regexp: '#unix_sock_rw_perms = "0770"'
        line: 'unix_sock_rw_perms = "0770"'

    - name: Add User to `libvirt` Group
      become: true
      become_user: root
      user:
        name: "{{ ansible_user_id }}"
        groups: libvirt
        append: true
      notify: Restart `libvirtd`

    - name: Start and Enable `libvirtd`
      become: true
      become_user: root
      service:
        name: libvirtd
        state: started
        enabled: true

    - name: Enable Kernel Module
      become: true
      become_user: root
      modprobe:
        name: kvm_intel
        state: present
        params: "nested=1"

    - name: Persist Kernel Module
      become: true
      become_user: root
      copy:
        content: "options kvm_intel nested=1"
        dest: /etc/modprobe.d/kvm-intel.conf

  handlers:
    - name: Update Packages
      shell: |
        #!/bin/sh
        /usr/bin/paru -Syu --noconfirm

    - name: Install Missing Packages
      shell: |
        #!/bin/sh
        /usr/bin/paru -S $(echo "{{ missing_packages.stdout_lines | join(' ') }}") --noconfirm

    - name: Restart `libvirtd`
      become: true
      become_user: root
      service:
        name: libvirtd
        state: restarted
